network:
  name: "Ethereum Mainnet"
  chain_id: 1
  rpc_url: "https://eth-mainnet.g.alchemy.com/v2/your-api-key"

contract:
  address: "0x2f3044FC6B38E662066601833878bB32C1897931" # Example Allocation Contract
  abi_path: "./core/abi.json"

settings:
  min_balance_required: 0.005
  auto_gas_optimization: true
  region: "BR-LATAM"
